**TASK:** import numpy

In [1]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [2]:
x = np.array([1, 2, 3])


**TASK:** define (2 x 2) matrix 'A' 


In [6]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

**TASK:** define (2 x 2) matrix 'B'

In [8]:
B = np.array ([[5,7],[4,9]])
B

array([[5, 7],
       [4, 9]])

**TASK:** check the type of 'x'

In [9]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [10]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [11]:
x.shape

(3,)

**TASK:** check the type of 'A'

In [12]:
A.shape

(2, 2)

**TASK:** 

In [ ]:
"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

In [43]:
def have_same_shape (x,y):
    if x.shape == y.shape :
        return True
    else:
        print('Arrays must have same shape!')
        return False

**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [44]:
have_same_shape(A,x)

Arrays must have same shape!


False

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [45]:
have_same_shape(A,B)

True

**TASK:** 

In [ ]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""


In [65]:
def matrix_addition(A,B):
    if have_same_shape(A,B) == True:
        C = A + B
        return C
       
      

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [68]:
matrix_addition(A,B)

array([[ 6,  9],
       [ 7, 13]])

**TASK:** 

In [1]:
"""
Define 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

"\nDefine 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition\n\nPARAMS:\n   lst_of_arr (list) - list of numpy.ndarrays\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new array\n\nUse 'matrix_addition' function defined before.\n"

In [78]:
def multiple_matrix_adition(lst_of_arr):
    if len(lst_of_arr) >= 2:
        z = lst_of_arr[0]
        w = lst_of_arr[1]                       
        NEW_ARRAY = matrix_addition(z,w)
        for i in (lst_of_arr[2:]):
            NEW_ARRAY = matrix_addition(NEW_ARRAY,i)
        return NEW_ARRAY
    else:
        return False
            
  



    
    
    

**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [89]:
multiple_matrix_adition([A,A,B,B,B])

array([[17, 25],
       [18, 35]])

**TASK:** 

In [ ]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

In [126]:
def can_multiply(first_array,second_array):
    try:
        C = first_array.dot(second_array)
        print('shape of array :', C.shape)
        return True
    except:
        print("Matrices can not be multiplied")
        return False
    

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [127]:
can_multiply(A,B)

shape of array : (2, 2)


True

**TASK:**  define matrix (3 x 2) matrix C

In [128]:
C = np.array([[1,2],[3,4],[5,5]])


**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [124]:
can_multiply(A,C)

Matrices can not be multiplied


False

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [129]:
can_multiply(C,A)

shape of array : (3, 2)


True

**TASK:** 

In [ ]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

In [132]:
def matrix_multiplication(array_a,array_b):
    if can_multiply(array_a,array_b) == True:
        NEW_ARRAY = array_a.dot(array_b)
        return NEW_ARRAY


**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [133]:
matrix_multiplication(C,B)

shape of array : (3, 2)


array([[13, 25],
       [31, 57],
       [45, 80]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [134]:
matrix_multiplication(A,C)

Matrices can not be multiplied
