# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [35]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [36]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [37]:
a = np.arange(10,49)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [38]:
new_arr=np.array(['A','L','E','X'])
print(new_arr)
reversed_arr=np.flip(new_arr)
print(reversed_arr)

['A' 'L' 'E' 'X']
['X' 'E' 'L' 'A']


#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [39]:
matri3x3 = np.arange(0,9).reshape((3,3))
matri3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [40]:
arraysample = np.array([1,2,0,0,4,0])
np.argwhere(arraysample != 0)


array([[0],
       [1],
       [4]], dtype=int64)

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [41]:
vector333 = np.random.random((3,3,3))
vector333

array([[[0.53116666, 0.18478797, 0.20164661],
        [0.37596641, 0.6338332 , 0.35835374],
        [0.81541426, 0.51055893, 0.45054514]],

       [[0.47748091, 0.10696796, 0.89481862],
        [0.92737278, 0.46093505, 0.62678673],
        [0.93585901, 0.52354992, 0.68500524]],

       [[0.55212322, 0.70973434, 0.93080842],
        [0.86940189, 0.16707204, 0.99669773],
        [0.47982223, 0.26369442, 0.75029541]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [43]:

b = np.random.randint(10,90,(10,10))

c = np.min(b)
d = np.max(b)
b, c, d


(array([[19, 49, 38, 87, 22, 47, 23, 84, 80, 59],
        [45, 10, 39, 62, 26, 18, 10, 42, 85, 72],
        [65, 71, 30, 63, 53, 31, 62, 21, 89, 20],
        [31, 64, 77, 40, 37, 20, 34, 13, 27, 43],
        [35, 47, 59, 22, 38, 12, 41, 53, 37, 41],
        [27, 40, 77, 23, 41, 59, 11, 66, 55, 55],
        [47, 49, 17, 12, 69, 60, 74, 41, 84, 78],
        [78, 46, 62, 59, 27, 39, 77, 85, 12, 52],
        [16, 61, 20, 24, 76, 49, 50, 87, 46, 25],
        [13, 80, 12, 85, 73, 20, 66, 57, 80, 80]]),
 10,
 89)

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [51]:
randomvector = np.random.randint(9,56,(30))
promedio = np.mean(randomvector)
randomvector, promedio


(array([22,  9, 25, 46, 26,  9, 45, 45, 27, 35, 41, 33, 34, 26, 47, 54, 27,
        13, 48, 15, 55, 22, 29, 45, 22, 28, 30, 12, 54, 26]),
 31.666666666666668)

#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [54]:
array2d = np.ones((5,5))
array2d[1:4,1:4] = 0
array2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [82]:
f = np.ones((5,5))
f = np.pad(f, pad_width=1, mode='constant',
               constant_values=0)

f

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [73]:
nan, False,False,nan,True,False

nan

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [77]:
matrix5per5 = np.ones((5,5))
matrix5per5
matrix5per5 [[1,2,3,4],[0,1,2,3]] = 1,2,3,4
matrix5per5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 1., 3., 1., 1.],
       [1., 1., 1., 4., 1.]])

#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [78]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 16. Normalize a 5x5 random matrix (★☆☆)

In [80]:
ran_two_array = np.random.rand(5, 5)*10 
print(ran_two_array)
norm = np.linalg.norm(ran_two_array)       
print(norm)                                
normalized_array = ran_two_array/norm   
print(normalized_array)

[[3.09907298 5.82612455 6.03116552 5.11570912 6.58524673]
 [8.45949387 7.86253608 3.10246665 3.76531229 5.65686688]
 [8.79041311 5.02526398 6.73057216 1.19183532 3.92199995]
 [1.36473731 0.71037342 4.19920677 0.12707322 4.51800448]
 [5.41746726 4.71667979 3.03887383 5.42469193 6.73479945]]
26.063706313047557
[[0.11890377 0.223534   0.23140092 0.19627712 0.25265964]
 [0.32456987 0.30166608 0.11903398 0.14446573 0.21704   ]
 [0.33726643 0.19280696 0.25823542 0.04572778 0.15047745]
 [0.0523616  0.02725527 0.16111319 0.00487549 0.17334467]
 [0.20785483 0.18096735 0.11659408 0.20813202 0.25839761]]


#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [83]:
array1D = np.arange(11)

array1D[3:9] = np.multiply(array1D[3:9],-1)

print(array1D)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 18. How to round away from zero a float array ? (★☆☆)

In [84]:
A = np.array((0.4,  1.6, 2.1, -0.7, 0.9))
np.around(A)

array([ 0.,  2.,  2., -1.,  1.])

#### 19. Find common values between two arrays? (★☆☆)

In [85]:
y = np.array([2, 4, 7, 1, 4])
z = np.array([7, 2, 9, 0, 5])
w = np.intersect1d(y, z)
w

array([2, 7])

#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [86]:
False, invalid value

<ipython-input-86-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [89]:
import random
mylist = []

def myarray():
    for i in range(0,10):
        n = random.randint(1,30)
        mylist.append(n)
    my_array = np.array(mylist)
    return my_array
myarray()
    

array([ 6, 26, 16, 18,  9, 18, 28, 16, 16,  4])

#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [90]:
vector = np.linspace(0,1,12)[1:-1]
vector

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 23. Create a random vector of size 10 and sort it (★★☆)

In [97]:
randomvector10 = np.sort(np.random.randint(5,20,(10)))

randomvector10

array([ 6,  6,  7,  7,  9, 13, 15, 15, 18, 19])

#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [100]:
a1 = np.array([1,2,4,6,7])
a2 = np.array([1,2,4,5,7])
np.array_equal(a1,a2)

False

#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [113]:
ranvec10 = np.random.randint(5,20,(10))
print(ranvec10)
ranvec10[np.argmax(ranvec10)] = 0
ranvec10





[18 17  7 11 11 10 14  5 15  5]


array([ 0, 17,  7, 11, 11, 10, 14,  5, 15,  5])

#### 26. Find the closest value to random element in a vector? (★★☆)

In [118]:
arr = np.array([9, 76, 16, 59, 39, 49])
print("Array is : ", arr)
#Closest Value
close_value = 60
#Calculate the smallest difference to that value
difference_array = np.absolute(arr-close_value)
print(difference_array)
index = difference_array.argmin()
index

Array is :  [ 9 76 16 59 39 49]
[51 16 44  1 21 11]


3

#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [120]:
Z = np.arange(10, dtype=np.float32)

Z = Z.astype(np.int32, copy=False)

print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 28. Sort an array by the nth column? (★★☆)

In [145]:
nums = np.random.randint(0,10,(3,3))
print(nums)
nums[np.argsort(nums[:, 1])]


[[7 3 6]
 [0 3 7]
 [0 9 9]]


array([[7, 3, 6],
       [0, 3, 7],
       [0, 9, 9]])

#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

In [149]:
arraywithnull = np.random.randint(0,3,(3,10)).astype(float)
arraywithnull[:,0:2] = np.nan
print(arraywithnull)
G = np.isnan(arraywithnull)
print((G.all(axis=0)).any())

[[nan nan  0.  1.  0.  0.  0.  2.  1.  1.]
 [nan nan  1.  1.  1.  1.  2.  0.  1.  2.]
 [nan nan  2.  1.  1.  0.  1.  1.  2.  2.]]
True


#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [200]:
arrayinterleaved = np.array([1,2,3,4,5])
numberzeros = 3
Z0 = np.zeros(len(arrayinterleaved) + (len(arrayinterleaved)-1)*(numberzeros))
Z0[::numberzeros + 1] = arrayinterleaved
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 31. Swap two rows of an array? (★★★)

In [206]:
originalarray = np.array([[4,3,1], [5,7,0], [9,9,3], [8,2,4]])
print(originalarray)
originalarray[[0, 1]] = originalarray[[1, 0]]
print(originalarray)


[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]
[[5 7 0]
 [4 3 1]
 [9 9 3]
 [8 2 4]]


#### 32. How to negate a boolean value inside an array? (★★★)

In [211]:
negarray = np.array([True, False])
negarray = np.invert(negarray)
print(negarray)

[False  True]


#### 33. Find the most frequent value in an array?

In [215]:
g = np.array([1, 1, 1, 2, 3, 4,4, 2, 4, 3, ])
print(g)
#Most frequent value
counter = np.bincount(g)
print(counter)
maxvalue = max(counter)
for i in range(len(counter)):
    if counter[i] == maxvalue:
        print(i, end=" ")


[1 1 1 2 3 4 4 2 4 3]
[0 3 2 2 3]
1 4 

#### 34. Get the n largest values of an array (★★★)

In [220]:
arr = np.array([2, 0,  1, 5, 4, 1, 9])
sorted_index_array = np.argsort(arr)
print(sorted_index_array)
# sorted array
sort_array = arr[sorted_index_array]
print(sorted_array)
#largests values
largestvalue = 1
largestvalues = sort_array[-largestvalue : ]
print(largestvalues)

[1 2 5 0 4 3 6]
[0 1 1 2 4 5 9]
[9]


#### 35. Extract unique rows from a two dimensional array? (★★★)

In [224]:
arr2D = np.array([[11, 11, 12, 11],
                     [13, 11, 12, 11],
                     [16, 11, 12, 11],
                     [11, 11, 12, 11],
                      [16, 11, 12, 11]])
print(arr2D)
#Get uniqueros
uniqueRows = np.unique(arr2D, axis = 0)
print(uniqueRows)

[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]
 [11 11 12 11]
 [16 11 12 11]]
[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]]
